### ISSUE TITLE
Improve subo-generated SCN manifest 

### ISSUE THREAD

**Issue by flaki** [suborbital/subo#331]
As mentioned in suborbital/docs#154 we should consider updating the `subo`-generated templates adding the non-autocert option for the builder. We should consider which usecase to make default, but can also inline the commented-out other configuration in the manifest for ease of switching.

Relevant snippets of the current [scc-controlplane-deployment.yaml template](https://github.com/suborbital/subo/blob/main/templates/scc-k8s/.suborbital/scc-controlplane-deployment.yaml.tmpl):

```
          ports:
            - containerPort: 8080
            - containerPort: 8443


          env:
            - name: SCC_DOMAIN
              value: "{{ .BuilderDomain }}"


            - name: SCC_TLS_PORT
              value: "8443"
```

```
    - protocol: TCP
      name: challenge
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8443
```
